version bump
jenkinsci/browserstack-integration-plugin pull request #25
Opened 2020-10-20 09:05 UTC by SaranshBS

2020-10-20 09:06 UTC, yashLadha approved these changes

2020-10-20 09:07 UTC, raghuhit approved these changes

2020-10-20 11:04 UTC, yashLadha requested changes

2020-10-20 11:04 UTC, yashLadha commented on pom.xml
> +  <version>1.1.8-SNAPSHOT</version>
```suggestion
  <version>1.1.9-SNAPSHOT</version>
```

As `1.1.8` is released.

2020-10-21 06:38 UTC, raghuhit approved these changes

2020-10-21 10:19 UTC, merged