BrowserStack Reports retention
jenkinsci/browserstack-integration-plugin pull request #71
Opened 2023-07-06 08:54 UTC by kamal-kaur04

Create Persistent BrowserStack Reports.

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-07-06 16:09 UTC, karanshah-browserstack requested changes

2023-07-06 16:09 UTC, karanshah-browserstack commented on src/main/java/com/browserstack/automate/ci/common/constants/Constants.java
> +    public static final String BROWSERSTACK_REPORT_PATH_PATTERN = "**/browserstack-artifacts/*";
Might break in windows machine

2023-07-07 04:56 UTC, karanshah-browserstack commented on src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackReportForBuild.java
> +                paths = bstackDir.list("buildResults*.json");
Why is this * ?

2023-07-07 06:30 UTC, kamal-kaur04 commented on src/main/java/com/browserstack/automate/ci/common/constants/Constants.java
> +    public static final String BROWSERSTACK_REPORT_PATH_PATTERN = "**/browserstack-artifacts/*";
This is working on windows.

2023-07-07 07:12 UTC, karanshah-browserstack approved these changes

2023-07-07 14:05 UTC, merged